### ISSUE TITLE
The id key in the android client is incorrect, making all requests to the server fail

### ISSUE THREAD

**Issue by NamanShergill** [mostafamvh/traccar_flutter#2]
https://github.com/traccar/traccar-client-android/blob/d4a4dbfd56c5a7ea19391bb5de252c9cd8aa7938/app/src/main/java/org/traccar/client/ProtocolFormatter.kt#L25

https://github.com/mostafamvh/traccar_flutter/blob/c06d739ad48b879bc3ac6ff066ffbe1c112126d5/android/src/main/kotlin/dev/mostafamovahhed/traccar_flutter/client/ProtocolFormatter.kt#L25

`UnidId` instead of `id`

**Comment by mostafamvh** [comment]
Hi,
Thank you. I’ve reviewed your contribution, and I appreciate your effort!

**Comment by mostafamvh** [comment]
> https://github.com/traccar/traccar-client-android/blob/d4a4dbfd56c5a7ea19391bb5de252c9cd8aa7938/app/src/main/java/org/traccar/client/ProtocolFormatter.kt#L25
> 
> https://github.com/mostafamvh/traccar_flutter/blob/c06d739ad48b879bc3ac6ff066ffbe1c112126d5/android/src/main/kotlin/dev/mostafamovahhed/traccar_flutter/client/ProtocolFormatter.kt#L25
> 
> `UnidId` instead of `id`

Hi,
Thank you. I’ve reviewed your contribution, and I appreciate your effort!

Version "1.0.2+4" published.
